### ISSUE TITLE
 Node.js Quickstart example in Google Calendar API is not working with parameters

### ISSUE THREAD

**Issue by fulya35** [google/google-api-nodejs-client#1041]
Hi,
In Google Calendar API  Node.js Quickstart example, when `calendar.events.list()` method is called with different parameters values for `timeMin` and `maxResults`, returned result is not affected with these changes.Always returns my all events.

```
function listEvents(auth) {
  var calendar = google.calendar('v3');
  calendar.events.list({
    auth: auth,
    calendarId: 'primary',
    timeMin: (new Date()).toISOString(),
    maxResults: 4,
    singleEvents: true,
    orderBy: 'startTime'
  }, function(err, response) {
    if (err) {
      console.log('The API returned an error: ' + err);
      return;
    }
    var events = response.items;
    if (events.length == 0) {
      console.log('No upcoming events found.');
    } else {
      console.log('Upcoming 4 events:');
      for (var i = 0; i < events.length; i++) {
        var event = events[i];
        var start = event.start.dateTime || event.start.date;
        console.log('%s - %s', start, event.summary);
      }
    }
  });
}
```

Thanks!

**Comment by dukeks** [comment]
I have the exact same problem. It's not just you :(

**Comment by dukeks** [comment]
After a long time of googling I found the solution at stackoverflow. The way you have to define the query has changed. Have a look at this thread: https://stackoverflow.com/questions/48488105/google-calendar-api-v3-doesnt-respect-timemin-timemax-parameters-in-nodejs-expr

**Comment by fulya35** [comment]
@dukeks , thank you! it is worked.

**Comment by JustinBeckwith** [comment]
Greetings! Can you share a link to the quickstart you're following?  And provide the error you're getting?  Thanks!

**Comment by jackgray** [comment]
It's THE quickstart guide for Node and Google Calendar API. I can only fine
one, but here is the link.

https://developers.google.com/calendar/quickstart/nodejs

According to my troubleshooting research, this has been a problem for quite
some time. There are many posts about this in the github issues section of
these libraries.

https://github.com/google/google-auth-library-nodejs/issues/251


"

/Users/jackgray/webapps/bcd/server/quickstart.js:5

const OAuth2Client = google.auth.OAuth2;

                                 ^


TypeError: Cannot read property 'OAuth2' of undefined

    at Object.<anonymous>
(/Users/jackgray/webapps/bcd/server/quickstart.js:5:34)

    at Module._compile (module.js:643:30)

    at Object.Module._extensions..js (module.js:654:10)

    at Module.load (module.js:556:32)

    at tryModuleLoad (module.js:499:12)

    at Function.Module._load (module.js:491:3)

    at Function.Module.runMain (module.js:684:10)

    at startup (bootstrap_node.js:187:16)

    at bootstrap_node.js:608:3
"

**Comment by jackgray** [comment]
"dependencies": {
"body-parser": "^1.17.2",
"concurrently": "^3.5.0",
"cookie-session": "^2.0.0-beta.2",
"express": "^4.15.3",
"fs": "0.0.1-security",
"google-auth-library": "^0.12.0",
"googleapis": "^27.0.0",
"localtunnel": "^1.8.3",
"lodash": "^4.17.4",
"mkdirp": "^0.5.1",
"mongoose": "^4.11.1",
"nodemon": "^1.11.0",
"passport": "^0.3.2",
"path-parser": "^2.0.2",
"readlines": "^0.2.0",
"save": "^2.3.2",
"sendgrid": "^5.1.2",
"stripe": "^4.23.1"
}


Is there a particular version of Node I should be running? I have tried a
few old and new..

**Comment by JustinBeckwith** [comment]
Greetings!  The quickstart is out of date.  We're working to fix that :) You just need to change this:

```js
const google = require('googleapis');
```

To this:

```js
const {google} = require('googleapis');
```

Apologies for the trouble, and hope this helps!
