### ISSUE TITLE
Analytics Account Summary - Converting circular structure to JSON

### ISSUE THREAD

**Issue by camarrone** [google/google-api-nodejs-client#1069]
Hello,

I trying to get the accounts summaries from Analytics using the API (version 27.0.0) but I'm getting the following error:
```

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (/server/node_modules/express/lib/response.js:1119:12)
    at ServerResponse.json (/server/node_modules/express/lib/response.js:260:14)
    at ServerResponse.send (/server/node_modules/express/lib/response.js:158:21)
    at /server/routes/googleAnalytics.js:75:21
    at /server/node_modules/googleapis/node_modules/google-auth-library/build/src/auth/oauth2client.js:393:64
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

This is the code I'm using:

```
router.get('/googleanalytics/load/',function(req,res,next){

    user = {
        "access_token":data.Items[0].googleAccessToken,
        "refresh_token":data.Items[0].googleRefreshToken
    }

	oauth2Client.setCredentials({
	  access_token: user.access_token,
	  refresh_token: user.refresh_token,
	});

	googleAnalytics = google.analytics({
			version: 'v3',
			auth: oauth2Client
	});

      googleAnalytics.management.accounts.list( function(error, response) {
        if(error){
            console.log(error);
            res.status(500).send(error)
        }

        res.send({analyticsaccount: response});
    });
  
});
```

The same code works when I use versions 16.0.0 and 17.0.0.

Is there anyone facing this issue also?

Thanks!

**Comment by JustinBeckwith** [comment]
The 'response' object is now a complex object that has all the details of the response, not just the data.  Try res.sending response.data :)
