### ISSUE TITLE
Error: Required parameter: mimeType, even the fact it is provided.

### ISSUE THREAD

**Issue by luckylooke** [google/google-api-nodejs-client#1098]
I am creating new issue because I was able to track the code via chrome devtools, and it seems to me it is BE bug.

Previously I have mentioned it here: https://github.com/google/google-api-nodejs-client/issues/963#issuecomment-377154737

I used [this code](https://developers.google.com/drive/v3/web/quickstart/nodejs) with combination with [this code](https://github.com/google/google-api-nodejs-client/blob/53149a164ab2972c7f821bb98444efd643ae471e/samples/drive/export.js) as starting point. 

it looks like this:
```javascript
// taken from https://developers.google.com/drive/v3/web/quickstart/nodejs

const fs = require('fs');
const path = require('path');
const os = require('os');
const uuid = require('uuid');
const readline = require('readline');
const google = require('googleapis');
const googleAuth = require('google-auth-library');

// If modifying these scopes, delete your previously saved credentials
// at ~/.credentials/drive-nodejs-quickstart.json
const SCOPES = [
    // 'https://www.googleapis.com/auth/drive',
    // 'https://www.googleapis.com/auth/drive.appdata',
    // 'https://www.googleapis.com/auth/drive.file',
    // 'https://www.googleapis.com/auth/drive.metadata',
    // 'https://www.googleapis.com/auth/drive.metadata.readonly',
    // 'https://www.googleapis.com/auth/drive.photos.readonly',
    'https://www.googleapis.com/auth/drive.readonly'
  ];
const TOKEN_DIR = './.credentials/';
const TOKEN_PATH = TOKEN_DIR + 'drive-nodejs-quickstart.json';

// Load client secrets from a local file.
fs.readFile('client_secret.json', function processClientSecrets(err, content) {
  if (err) {
    console.log('Error loading client secret file: ' + err);
    return;
  }
  // Authorize a client with the loaded credentials, then call the
  // Drive API.
  // authorize(JSON.parse(content), listFiles);
  // authorize(JSON.parse(content), listMajors);
  authorize(JSON.parse(content), (oauth2Client) => {
    const drive = google.drive({
      version: 'v3',
      // auth: sampleClient.oAuth2Client
      auth: oauth2Client
    });

    downloadFile(drive, '1n_8B1lQuXf69zfTwzvBMDkLFckeDq-UxnTvFaffWZvk', () => {
      console.log('test file donwloaded');
    });
  });
});

/**
 * Create an OAuth2 client with the given credentials, and then execute the
 * given callback function.
 *
 * @param {Object} credentials The authorization client credentials.
 * @param {function} callback The callback to call with the authorized client.
 */
function authorize(credentials, callback) {
  var clientSecret = credentials.installed.client_secret;
  var clientId = credentials.installed.client_id;
  var redirectUrl = credentials.installed.redirect_uris[0];
  var auth = new googleAuth();
  var oauth2Client = new auth.OAuth2(clientId, clientSecret, redirectUrl);

  // Check if we have previously stored a token.
  fs.readFile(TOKEN_PATH, function(err, token) {
    if (err) {
      getNewToken(oauth2Client, callback);
    } else {
      oauth2Client.credentials = JSON.parse(token);
      callback(oauth2Client);
    }
  });
}

/**
 * Get and store new token after prompting for user authorization, and then
 * execute the given callback with the authorized OAuth2 client.
 *
 * @param {google.auth.OAuth2} oauth2Client The OAuth2 client to get token for.
 * @param {getEventsCallback} callback The callback to call with the authorized
 *     client.
 */
function getNewToken(oauth2Client, callback) {
  var authUrl = oauth2Client.generateAuthUrl({
    access_type: 'offline',
    scope: SCOPES
  });
  console.log('Authorize this app by visiting this url: ', authUrl);
  var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  rl.question('Enter the code from that page here: ', function(code) {
    rl.close();
    oauth2Client.getToken(code, function(err, token) {
      if (err) {
        console.log('Error while trying to retrieve access token', err);
        return;
      }
      oauth2Client.credentials = token;
      storeToken(token);
      callback(oauth2Client);
    });
  });
}

/**
 * Store token to disk be used in later program executions.
 *
 * @param {Object} token The token to store to disk.
 */
function storeToken(token) {
  try {
    fs.mkdirSync(TOKEN_DIR);
  } catch (err) {
    if (err.code != 'EEXIST') {
      throw err;
    }
  }
  fs.writeFile(TOKEN_PATH, JSON.stringify(token));
  console.log('Token stored to ' + TOKEN_PATH);
}

/**
 * Lists the names and IDs of up to 10 files.
 *
 * @param {google.auth.OAuth2} auth An authorized OAuth2 client.
 */
function listFiles(auth) {
  var service = google.drive('v3');
  service.files.list({
    auth: auth,
    pageSize: 10,
    fields: "nextPageToken, files(id, name)"
  }, function(err, response) {
    if (err) {
      console.log('The API returned an error: ' + err);
      return;
    }
    var files = response.files;
    if (files.length == 0) {
      console.log('No files found.');
    } else {
      console.log('Files:');
      for (var i = 0; i < files.length; i++) {
        var file = files[i];
        console.log('%s (%s)', file.name, file.id);
      }
    }
  });
}

// src: https://github.com/google/google-api-nodejs-client/blob/master/samples/drive/download.js
function downloadFile (drive, fileId, callback) {
  // const filePath = path.join(os.tmpdir(), uuid.v4());
  const filePath = path.join(__dirname, 'test' + uuid.v4() + '.csv');
  console.log(`writing to ${filePath}`);
  const dest = fs.createWriteStream(filePath);
  let progress = 0;
  // https://github.com/google/google-api-nodejs-client/blob/53149a164ab2972c7f821bb98444efd643ae471e/samples/drive/export.js
  // https://developers.google.com/drive/v3/web/manage-downloads#downloading_google_documents
  drive.files.export({
      fileId: fileId,
      mimeType: 'text/csv' // <----------------------------------- MIME type PROVIDED, look ma :)
  }, {
      responseType: 'stream'
  },function(err, response){
      if(err) throw err;

      response.data.on('error', err => {
          console.error('Error downloading file.');
          throw err;
      }).on('end', ()=>{
          console.log('Done downloading file.');
          callback(filePath);
      })
      .pipe(dest);
  });
}
```
but getting error:
```
quickstart.js:166
      if(err) throw err;
              ^

Error: Required parameter: mimeType
    at RequestError.Error (native)
    at new RequestError (/path/node_modules/google-auth-library/lib/transporters.js:34:42)
    at Request._callback (/path/node_modules/google-auth-library/lib/transporters.js:96:27)
    at Request.self.callback (/path/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/path/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/path/node_modules/request/request.js:1085:12)
```
I was inspecting the code by using:
`node --inspect --debug-brk quickstart.js`
steping trough export method and mimeType was all the time there.. 
I dont know how to check the request from node using this example code.. because the devTools does not have network tab in this mode :/ 
But it really seems the error comes from backend.
Or at least could you provide me a hint how to check the request send to BE, wheather it has mimeType param attached? 

Many thanks :)

**Comment by luckylooke** [comment]
I have also found the [SO question here](https://stackoverflow.com/questions/49447186/exporting-file-from-google-drive-using-googleapi-in-node-js) The answer provided did not helped.

**Comment by JustinBeckwith** [comment]
Greetings!  We have a working example of this right a here:
https://github.com/google/google-api-nodejs-client/blob/master/samples/drive/export.js

From your callstack, it looks like either a.) you have an old version of googleapis installed, or b.) you have an old version of google-auth-library installed. 

Check to make sure in your package.json you have:
- Version 28.0.1 of googleapis
- NO VERSION of google-auth-library in your package.json.

Please try this and let me know how it goes 👍

**Comment by luckylooke** [comment]
I did not expected that I could have outdated packages.. because my colleague make the  repo just one or two weeks ago.. he made an example with listing the files from drive, my task is to export google docs sheet as csv into our node server.. so I am here now.. :)

after updating packages as you suggested, my code has this error:
```
quickstart.js:59
  var auth = new googleAuth();
             ^

TypeError: googleAuth is not a constructor
    at authorize (/path/quickstart.js:59:14)
    at processClientSecrets (/path/quickstart.js:35:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)
```
and so I was trying to make your example from link to work, and I am stuck in there too, on:
```
400. That’s an error.
Error: invalid_request
Missing required parameter: client_id
```
even the fact that there is clinet_id in oauth2.keys.json, under web namespace as your sampleClient is expecting.. :/ 

All I need is to read a sheet as csv, why is this so hard :/
