### ISSUE TITLE
Sample code does not running.

### ISSUE THREAD

**Issue by fs-takada** [google/google-api-nodejs-client#1106]
When I'm trying to run sample code, the following error appeared.

```
/Users/RN-161/Desktop/cloudFunction/test_googleapi.js:2
var compute = google.compute('v1');
                     ^

TypeError: google.compute is not a function
    at Object.<anonymous> (/Users/RN-161/Desktop/cloudFunction/test_googleapi.js:2:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

The url you were viewing
https://cloud.google.com/compute/docs/reference/rest/v1/instances/start 
  Example node.js

my env
npm: 5.8.0
node.js: v8.11.1

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share your full code sample?  Sometimes you'll run into this if you import the library incorrectly. Please make sure that:

- You import the lib using `const {google} = require('googleapis');`
- You DO NOT have `google-auth-library` in your package.json.

Short of that - a more complete code sample would be very helpful :)

**Comment by fs-takada** [comment]
Thank you for the reply.

▼test_googleapi.js
```
var google = require('googleapis');
var compute = google.compute('v1');

authorize(function(authClient) {
  var request = {
    // Project ID for this request.
    project: 'my-project',  // TODO: Update placeholder value.

    // The name of the zone for this request.
    zone: 'my-zone',  // TODO: Update placeholder value.

    // Name of the instance resource to start.
    instance: 'my-instance',  // TODO: Update placeholder value.

    auth: authClient,
  };

  compute.instances.start(request, function(err, response) {
    if (err) {
      console.error(err);
      return;
    }

    // TODO: Change code below to process the `response` object:
    console.log(JSON.stringify(response, null, 2));
  });
});

function authorize(callback) {
  google.auth.getApplicationDefault(function(err, authClient) {
    if (err) {
      console.error('authentication failed: ', err);
      return;
    }
    if (authClient.createScopedRequired && authClient.createScopedRequired()) {
      var scopes = ['https://www.googleapis.com/auth/cloud-platform'];
      authClient = authClient.createScoped(scopes);
    }
    callback(authClient);
  });
}
```

▼package.json
```
{
  "name": "cloudfunction",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@google-cloud/compute": "^0.10.0",
    "googleapis": "^28.1.0",
    "request": "^2.85.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by JustinBeckwith** [comment]
Thanks!  This:

```js
var google = require('googleapis');
```

Should be this:

```js
const {google} = require('googleapis');
```

Hope this helps :)

**Comment by fs-takada** [comment]
I was able to move it.
Thank you!
