### ISSUE TITLE
promisify function but this.getRoot is undefined

### ISSUE THREAD

**Issue by HoKangInfo** [google/google-api-nodejs-client#1116]
v28.1.0
```
const promisify = require('util').promisify;
promisify(drive.files.create);
```
TypeError: Cannot read property 'getRoot' of undefined
    at Resource$Files.create (/home/robin/kapi/node_modules/googleapis/build/src/apis/drive/v3.js:452:27)

but v27.0.0 is OK
diff v28 use `this` v27 use `self`.

v28.1.0 can use
```
promisify(drive.files.create.bind(drive));
```

**Comment by JustinBeckwith** [comment]
Good news!  You don't need to promisify anymore :)   The API will return a promise for you if you don't pass a callback.  Can you try just dropping the promise wrapping code?

**Comment by HoKangInfo** [comment]
good! it work.

**Comment by amaranadh-wal** [comment]
Hi @JustinBeckwith I have the same issue while working google analytics. 

` google.analyticsreporting('v4').reports.batchGet({
    resource: {
      'reportRequests': [{
        'dateRanges': [{
          startDate,
          'endDate': 'today'
        }],
        'viewId': config.gaRealtimeIds,
        'metrics': [{'expression': 'ga:pageviews'}],
        'dimensions': [{'name': 'ga:pagePath'}],
        'hideTotals': true,
        'hideValueRanges': true,
        'dimensionFilterClauses': [{
          'filters': paths.map(path => ({
            'expressions': path,
            'operator': 'PARTIAL',
            'dimensionName': 'ga:pagePath'
          }))
        }]
      }]
    }
  })`

Can you please suggest the fix for me.

**Comment by JustinBeckwith** [comment]
Greetings @amaranadh-wal!  If you're having issues please open a new issue with:
1. A complete-ish code sample
2. The version of nodejs and of googleapis you're using
3. The exact error you're getting in the console with a call stack

**Comment by amaranadh-wal** [comment]
```
const oauth2Client = new google.auth.OAuth2(gaClientId, gaClientSecret, gaRedirectUrl)
  oauth2Client.setCredentials({refresh_token: gaRefreshToken})
  google.options({auth: oauth2Client})

  google.analyticsreporting('v4').reports.batchGet({
    resource: {
      'reportRequests': [{
        'dateRanges': [{
          startDate,
          'endDate': 'today'
        }],
        'viewId': config.gaRealtimeIds,
        'metrics': [{'expression': 'ga:pageviews'}],
        'dimensions': [{'name': 'ga:pagePath'}],
        'hideTotals': true,
        'hideValueRanges': true,
        'dimensionFilterClauses': [{
          'filters': paths.map(path => ({
            'expressions': path,
            'operator': 'PARTIAL',
            'dimensionName': 'ga:pagePath'
          }))
        }]
      }]
    }
  })

```


**Error:** 
     TypeError: Cannot read property 'getRoot' of undefined
      at batchGet (node_modules/googleapis/src/apis/analyticsreporting/v4.ts:1023:23)

**Comment by amaranadh-wal** [comment]
@JustinBeckwith Please take a look at above information.

**Comment by JustinBeckwith** [comment]
How are you getting the result back?  Have you tried await-ing the call?

```js
const res = await google.analyticsreporting('v4').reports.batchGet({
...
```

**Comment by amaranadh-wal** [comment]
Yes. I missed that while doing copy and paste.

**Comment by amaranadh-wal** [comment]
Hi @JustinBeckwith did you get any clue regarding this ?

**Comment by pmuens** [comment]
@amaranadh-wal I faced the same error. My solution was to use `bind` since I'm using `reduce`. 

Here's my solution:

```js
const _ = require('lodash');
const google = require('googleapis').google;

this.sdk = {
    deploymentmanager: google.deploymentmanager('v2'),
    storage: google.storage('v1'),
    logging: google.logging('v2'),
};

const filArgs = ['deploymentmanager', 'deployments', 'list'];
const params = {
  // your reqest parameters
}

const service = filArgs[0];
const serviceInstance = this.sdk[service];

return authClient.authorize().then(() => {
  const requestParams = { auth: authClient };
  _.merge(requestParams, params);

  // this fails
  // return filArgs.reduce(((p, c) => p[c]), this.sdk)(requestParams)

  // this works (notice the `bind` to the `serviceInstance`)
  return filArgs.reduce(((p, c) => p[c]), this.sdk).bind(serviceInstance)(requestParams)
});
```

Hope that it helps...

**Comment by amaranadh-wal** [comment]
@pmuens Thanks for the response. I just found the problem. 
I am working with babel-node. I am getting above problem when I am using inside a promise.
