### ISSUE TITLE
Run Google Apps Script Externally using node.js

### ISSUE THREAD

**Issue by wakanakaTaka** [google/google-api-nodejs-client#1175]
const {google} = require('googleapis');
const path = require('path');

/**
 * The JWT authorization is ideal for performing server-to-server
 * communication without asking for user consent.
 *
 * Suggested reading for Admin SDK users using service accounts:
 * https://developers.google.com/admin-sdk/directory/v1/guides/delegation
 *
 * See the defaultauth.js sample for an alternate way of fetching compute credentials.
 */
async function runSample () {
    // Create a new JWT client using the key file downloaded from the Google Developer Console
    const client = await google.auth.getClient({
        keyFile: path.join(__dirname, 'projectmayhemserviceaccountkey.json'),
        scopes: ['https://www.googleapis.com/auth/script.send_mail',
        'https://www.googleapis.com/auth/spreadsheets']
    });

    // Obtain a new drive client, making sure you pass along the auth client
    const script = google.script({
        version: 'v1',
        //auth: client,
        //scriptId:'161Fz0bbfidXzkpbJ5szhfUd6MEJecolBMwr1GD03LFCesQ4GztrfMynB'
    });
    //console.log(script);
    // Make an authorized request to list Drive files.
    const res = await script.scripts.run(
        {
            scriptId:'161Fz0bbfidXzkpbJ5szhfUd6MEJecolBMwr1GD03LFCesQ4GztrfMynB',
            auth: client,
            function: 'ConsolidateSheet'
        }
    );
    console.log(res.data);

    return res.data;
}
if (module === require.main) {
    runSample().catch(console.error);
}

Hi I'm trying to run function consolidate sheet the script.run method and I am getting an invalid argument message. I know I am missing something, but I can't seem to figure out which field is incorrect. (if i just try scriptid and auth, I also get an invalid argument error). Any help would be appreciated.

Thanks!

**Comment by wakanakaTaka** [comment]
```{ Error: Request contains an invalid argument.
    at createError (C:\Users\jordan.tang\TangDirectory\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\jordan.tang\TangDirectory\node_modules\axios\lib\core\settle.js:18:12)
    at Unzip.handleStreamEnd (C:\Users\jordan.tang\TangDirectory\node_modules\axios\lib\adapters\http.js:201:11)
    at emitNone (events.js:111:20)
    at Unzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: 2147483648,
     validateStatus: [Function],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/x-www-form-urlencoded',
        'Accept-Encoding': 'gzip',
        'User-Agent': 'google-api-nodejs-client/30.0.0 (gzip)',
        Authorization: 'Bearer ya29.c.Ely9BSiR8BV_0KRyGOy4EXrEksOcF2tG6HxQExg-UOwxNCoTEQ46gv8cuwCV5mQxhlI9fborOSPYmSUsqNyH6dCe2fKpw-LICIuYm7RQovGmZvz1VkejT638zZn0oQ' },
     method: 'post',
     url: 'https://script.googleapis.com/v1/scripts/161Fz0bbfidXzkpbJ5szhfUd6MEJecolBMwr1GD03LFCesQ4GztrfMynB:run',
     paramsSerializer: [Function],
     data: undefined,
     params: {} },
  request:
   ClientRequest {
     domain: null,
     _events:
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'script.googleapis.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 482,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 33,
        [Symbol(bytesRead)]: 805 },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'script.googleapis.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 482,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 33,
        [Symbol(bytesRead)]: 805 },
     _header: 'POST /v1/scripts/161Fz0bbfidXzkpbJ5szhfUd6MEJecolBMwr1GD03LFCesQ4GztrfMynB:run HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/x-www-form-urlencoded\r\nAccept-Encoding: gzip\r\nUser-Agent: google-api-nodejs-client/30.0.0 (gzip)\r\nAuthorization: Bearer ya29.c.Ely9BSiR8BV_0KRyGOy4EXrEksOcF2tG6HxQExg-UOwxNCoTEQ46gv8cuwCV5mQxhlI9fborOSPYmSUsqNyH6dCe2fKpw-LICIuYm7RQovGmZvz1VkejT638zZn0oQ\r\nHost: script.googleapis.com\r\nConnection: close\r\nContent-Length: 0\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '/v1/scripts/161Fz0bbfidXzkpbJ5szhfUd6MEJecolBMwr1GD03LFCesQ4GztrfMynB:run',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 400,
        statusMessage: 'Bad Request',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl: 'https://script.googleapis.com/v1/scripts/161Fz0bbfidXzkpbJ5szhfUd6MEJecolBMwr1GD03LFCesQ4GztrfMynB:run',
        read: [Function] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'https://script.googleapis.com/v1/scripts/161Fz0bbfidXzkpbJ5szhfUd6MEJecolBMwr1GD03LFCesQ4GztrfMynB:run' },
     [Symbol(outHeadersKey)]:
      { accept: [Array],
        'content-type': [Array],
        'accept-encoding': [Array],
        'user-agent': [Array],
        authorization: [Array],
        host: [Array] } },
  response:
   { status: 400,
     statusText: 'Bad Request',
     headers:
      { vary: 'Origin, X-Origin, Referer',
        'content-type': 'application/json; charset=UTF-8',
        date: 'Wed, 16 May 2018 19:05:00 GMT',
        server: 'ESF',
        'cache-control': 'private',
        'x-xss-protection': '1; mode=block',
        'x-frame-options': 'SAMEORIGIN',
        'x-content-type-options': 'nosniff',
        'alt-svc': 'hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35"',
        connection: 'close',
        'transfer-encoding': 'chunked' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: 2147483648,
        validateStatus: [Function],
        headers: [Object],
        method: 'post',
        url: 'https://script.googleapis.com/v1/scripts/161Fz0bbfidXzkpbJ5szhfUd6MEJecolBMwr1GD03LFCesQ4GztrfMynB:run',
        paramsSerializer: [Function],
        data: undefined,
        params: {} },
     request:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /v1/scripts/161Fz0bbfidXzkpbJ5szhfUd6MEJecolBMwr1GD03LFCesQ4GztrfMynB:run HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/x-www-form-urlencoded\r\nAccept-Encoding: gzip\r\nUser-Agent: google-api-nodejs-client/30.0.0 (gzip)\r\nAuthorization: Bearer ya29.c.Ely9BSiR8BV_0KRyGOy4EXrEksOcF2tG6HxQExg-UOwxNCoTEQ46gv8cuwCV5mQxhlI9fborOSPYmSUsqNyH6dCe2fKpw-LICIuYm7RQovGmZvz1VkejT638zZn0oQ\r\nHost: script.googleapis.com\r\nConnection: close\r\nContent-Length: 0\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/v1/scripts/161Fz0bbfidXzkpbJ5szhfUd6MEJecolBMwr1GD03LFCesQ4GztrfMynB:run',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Object],
        [Symbol(outHeadersKey)]: [Object] },
     data: { error: [Object] } },
  code: 400,
  errors:
   [ { message: 'Request contains an invalid argument.',
       domain: 'global',
       reason: 'badRequest' } ] }
```

Hi @JustinBeckwith,
Okay that library has been removed. Thanks for that note. I have also included the error message.

code: 400,
  errors:
   [ { message: 'Request contains an invalid argument.',
       domain: 'global',
       reason: 'badRequest' } ]

Thanks,

**Comment by wakanakaTaka** [comment]
Just want to make a note that I have tested the sample file for using jwt, and that does work.

https://github.com/google/google-api-nodejs-client/blob/master/samples/jwt.js 

So perhaps there is an issue with the script library?

**Comment by grant** [comment]
The Apps Script API is extremely fragile and will give red-herring errors if you don't call it properly.

Here's our official tutorial page:
https://developers.google.com/apps-script/api/how-tos/execute

For this example, it looks like you're missing the `resource` object in the request. That would make sense for a `badRequest` error.

I think this would be the solution, but I'm not sure:

```js
{
  scriptId:'161Fz0bbfidXzkpbJ5szhfUd6MEJecolBMwr1GD03LFCesQ4GztrfMynB',
  auth: client,
  resource: {
    function: 'ConsolidateSheet'
  },
}
```

and not

```js
{
  scriptId:'161Fz0bbfidXzkpbJ5szhfUd6MEJecolBMwr1GD03LFCesQ4GztrfMynB',
  auth: client,
  function: 'ConsolidateSheet'
}
```

(Here are [other examples](https://github.com/gsuitedevs/node-samples/search?q=%22++resource%3A+%7B%22&unscoped_q=%22++resource%3A+%7B%22) of this `resource` type)

There may be other issues. Here's the source for this run method in the Apps Script CLI:
https://github.com/google/clasp/blob/master/src/commands.ts#L270

**Comment by dobromyslov** [comment]
I got the same error "Request contains an invalid argument.". I've already red docs https://developers.google.com/admin-sdk/directory/v1/guides/delegation and https://developers.google.com/apps-script/api/how-tos/execute and seen a warning about service accounts there.

Does this Apps Script API not work with service accounts even in case the service account has domain-wide delegation? Please clarify.

**Comment by dobromyslov** [comment]
Did everything as described in https://developers.google.com/apps-script/api/quickstart/nodejs using G Suite admin user account instead of service account and everything works well now.

Is there any way to enable google service accounts for Apps Script execution?
