### ISSUE TITLE
Cannot Install Api via Scoped Package

### ISSUE THREAD

**Issue by samcrane8** [google/google-api-nodejs-client#1230]
I ran `npm install @google/calendar` and I got the following error:

```
CPLMAC0HFHV2T:core sam.crane$ npm install @google/calendar
npm ERR! code E404
npm ERR! 404 Not Found: @google/calendar@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sam.crane/.npm/_logs/2018-07-09T16_36_52_443Z-debug.log
CPLMAC0HFHV2T:core sam.crane$
```

the log is here: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/sam.crane/.nvm/versions/node/v8.11.2/bin/node',
1 verbose cli   '/Users/sam.crane/.nvm/versions/node/v8.11.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@google/calendar' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose npm-session e9585eec80749b5c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@google%2fcalendar 510ms
8 silly fetchPackageMetaData error for @google/calendar@latest 404 Not Found: @google/calendar@latest
9 verbose stack Error: 404 Not Found: @google/calendar@latest
9 verbose stack     at fetch.then.res (/Users/sam.crane/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/Users/sam.crane/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/Users/sam.crane/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/Users/sam.crane/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/Users/sam.crane/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/Users/sam.crane/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/Users/sam.crane/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/Users/sam.crane/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/Users/sam.crane/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:810:20)
9 verbose stack     at tryOnImmediate (timers.js:768:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
10 verbose cwd /Users/sam.crane/Documents/GitHub/soluto-api/packages/core
11 verbose Darwin 17.6.0
12 verbose argv "/Users/sam.crane/.nvm/versions/node/v8.11.2/bin/node" "/Users/sam.crane/.nvm/versions/node/v8.11.2/bin/npm" "install""@google/calendar"
13 verbose node v8.11.2
14 verbose npm  v5.6.0
15 error code E404
16 error 404 Not Found: @google/calendar@latest
17 verbose exit [ 1, true ]
```

Does this scoped package exist? The readme here says it should: https://github.com/google/google-api-nodejs-client/tree/master/src/apis/calendar

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  The scoped packages are not quite baked yet :) We're very much working on them, but for now we're tracking this over in #1260
