### ISSUE TITLE
Delete of an unqualified identifier in strict mode

### ISSUE THREAD

**Issue by jonlambert** [google/google-api-nodejs-client#458]
When importing and attempting to use the Google Plus API, in `iojs --harmony --use_strict` mode, it throws: 
```
/code/node_modules/googleapis/node_modules/google-auth-library/node_modules/gtoken/node_modules/google-p12-pem/node_modules/node-forge/js/forge.js:53
    delete define;
           ^^^^^^
SyntaxError: Delete of an unqualified identifier in strict mode.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:409:25)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/code/node_modules/googleapis/node_modules/google-auth-library/node_modules/gtoken/node_modules/google-p12-pem/index.js:1:75)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/code/node_modules/googleapis/node_modules/google-auth-library/node_modules/gtoken/lib/index.js:1:77)
    at Module._compile (module.js:426:26)
```

**Comment by ryanseys** [comment]
Should be filed against the project in question here, node-forge.
