### ISSUE TITLE
Cannot find module 'is-property'

### ISSUE THREAD

**Issue by ADSKLowenthal** [google/google-api-nodejs-client#486]
When running with the latest npm package `"googleapis": "^2.1.1"` I receive the error posted.
When I lock it to 2.1.1 `"googleapis": "2.1.1"` and do a fresh reinstall it runs as expected.

node 0.12.7
npm 2.11.3

This is the require and subsequent call for the blogger api, only place where we are using `googleapis`:
```
var google = require('googleapis');
var blogger = google.blogger('v3');
```

```
c:\dev\projects\gamedev-website\node_modules\q\q.js:155
                throw e;
                      ^
Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\dev\projects\gamedev-website\packages\custom\gdBlogs\node_modules\googleapis\node_modules\google-auth-library\node_modules\gtoken\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\dev\projects\gamedev-website\packages\custom\gdBlogs\node_modules\googleapis\node_modules\google-auth-library\node_modules\gtoken\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\index.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\dev\projects\gamedev-website\packages\custom\gdBlogs\node_modules\googleapis\node_modules\google-auth-library\node_modules\gtoken\node_modules\request\node_modules\har-validator\lib\index.js:5:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\dev\projects\gamedev-website\packages\custom\gdBlogs\node_modules\googleapis\node_modules\google-auth-library\node_modules\gtoken\node_modules\request\lib\har.js:5:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by JustinBeckwith** [comment]
This appears to be fixed with the current version.  I added a quick blogger sample here:
https://github.com/google/google-api-nodejs-client/tree/master/samples/blogger

If you're still having trouble, let us know!
