### ISSUE TITLE
Support for OAuth2 implicit flow/client-side apps flow

### ISSUE THREAD

**Issue by bnookala** [google/google-api-nodejs-client#529]
I'm building a client side application using the Calendar API. Since I don't want to bundle a client secret, I'm currently leaving it out when instantiating the OAuth client ie: 

`this.oauthClient = new OAuth2(this.oa2.clientID, undefined, this.oa2.redirectURI);`

This appears to work fine until the client token is requested with the auth code from the redirected URL via `this.oauthClient.getToken`, whereupon it fails with this error and trace:

```
Error: invalid_request
    at Request._callback (/Users/bhargav/code/waffle/node_modules/google-auth-library/lib/transporters.js:78:15)
    at Request.self.callback (/Users/bhargav/code/waffle/node_modules/google-auth-library/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/bhargav/code/waffle/node_modules/google-auth-library/node_modules/request/request.js:1057:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/bhargav/code/waffle/node_modules/google-auth-library/node_modules/request/request.js:1003:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

Adding the client secret to the the OAuth2 instantiation line appears to work swimmingly, and an access token is able to be retrieved.

Is there any intent for this library to support the OAuth2 client side application flow as [described by this doc](https://developers.google.com/identity/protocols/OAuth2UserAgent)?

**Comment by zweicoder** [comment]
Any updates on this? I'm encountering the same problem trying to avoid packaging the `client_secret` in my `Electron` app

**Comment by JustinBeckwith** [comment]
This issue was moved to google/google-auth-library-nodejs#299
