### ISSUE TITLE
oauth2 confusion

### ISSUE THREAD

**Issue by windmaple** [google/google-api-nodejs-client#569]
Hi,

I'm trying to run the 'oauth2.js' sample. I'm pretty sure I have put in the correct client ID/secret; I have also set REDIRECT_URL = 'urn:ietf:wg:oauth:2.0:oob'. No other change is made.

But I just keep getting this error:

An error occured Error: No access or refresh token is set.
    at OAuth2Client.getRequestMetadata (/Users/weiwe/WebstormProjects/adxseller2fbmessenger/node_modules/google-auth-library/lib/auth/oauth2client.js:271:23)
    at OAuth2Client.request (/Users/weiwe/WebstormProjects/adxseller2fbmessenger/node_modules/google-auth-library/lib/auth/oauth2client.js:358:15)
    at createAPIRequest (/Users/weiwe/WebstormProjects/adxseller2fbmessenger/node_modules/googleapis/lib/apirequest.js:180:22)
    at Object.Plus.self.people.get (/Users/weiwe/WebstormProjects/adxseller2fbmessenger/node_modules/googleapis/apis/plus/v1.js:227:14)
    at /Users/weiwe/WebstormProjects/adxseller2fbmessenger/oauth2.js:60:15
    at /Users/weiwe/WebstormProjects/adxseller2fbmessenger/oauth2.js:47:16
    at /Users/weiwe/WebstormProjects/adxseller2fbmessenger/node_modules/google-auth-library/lib/auth/oauth2client.js:154:5
    at Request._callback (/Users/weiwe/WebstormProjects/adxseller2fbmessenger/node_modules/google-auth-library/lib/transporters.js:67:30)
    at self.callback (/Users/weiwe/WebstormProjects/adxseller2fbmessenger/node_modules/google-auth-library/node_modules/request/request.js:198:22)
    at emitOne (events.js:96:13)

It seems it couldn't get the correct tokens; thus, when the code tries to retrieve Plus info, it throws the error. What am I doing wrong here?

**Comment by windmaple** [comment]
The weird thing is it works fine now, although I don't think I have made any chances ....
