### ISSUE TITLE
[Question] Nodejs server2server JWT authenticated admin.directory function fails returning 500

### ISSUE THREAD

**Issue by cedric-b** [google/google-api-nodejs-client#643]
I'm trying to get authenticated user roles using admin.directory.roleAssignments.list() function but thought the JWT authntication seems correct (a token is returned) the call to the function fails with a return code 500 and no explanation :

1. I've created a service account on the API console (making it proprietary of the project and given it DwD not sure it's required) and stored the json key file (the format seems OK :
```
{
  "type": "service_account",
  "project_id": "xxx",
  "private_key_id": "xxx",
  "private_key": "-----BEGIN PRIVATE KEY-----xxx-----END PRIVATE KEY-----\n",
  "client_email": "xxx",
  "client_id": "xxx",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/lptime-1343%40appspot.gserviceaccount.com"
}
```
2. installed and required googleapis
3. created the method to grant acces via JWT tioken based on the json keyfile and get user role assigment, using what I think to be correct scopes (see below) :
```
    var google = require('googleapis');
    var googleAuth = require('google-auth-library');
    var key = require(__dirname + '/Lptime-e660b18cf2f9.json');
    var directory = google.admin('directory_v1');
    var scopes = [
        'https://www.googleapis.com/auth/admin.directory.user',
        'https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly'
    ];

    var jwtClient = new google.auth.JWT(key.client_email, null, key.private_key, scopes, null);

    module.getRoles = function (id, cb) {
        console.log('entering module.getRoles: ' + id);
        jwtClient.authorize(function (err, tokens) {
            console.log('entering jwtClient.authorize');
            if (err) {
                cb(err);
            }
            console.log(tokens);
            var $params = {auth: jwtClient, customer: 'my_customer', userKey: id};
            directory.roleAssignments.list($params, function (err, roles) {
                console.log('returning from directory.roleAssignments.list');
                console.log(err);
                cb(err, roles);
            });
            return;
        });
    };
```
The code fails on getting the assignment (500 see here below), though the method  work using the googleAuth() authentication method with API clientID and clientSecret. Here is the log:
```
entering jwtClient.authorize
{ access_token: <token_hash>,
  token_type: 'Bearer',
  expiry_date: 1475526629000,
  refresh_token: 'jwt-placeholder' }
returning from directory.roleAssignments.list
{ [Error: null] code: 500 }
Error: null
    at Request._callback (/var/www/wlh.lptime.com/web/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:92:15)
    at Request.self.callback (/var/www/wlh.lptime.com/web/node_modules/googleapis/node_modules/google-auth-library/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/var/www/wlh.lptime.com/web/node_modules/googleapis/node_modules/google-auth-library/node_modules/request/request.js:1057:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/var/www/wlh.lptime.com/web/node_modules/googleapis/node_modules/google-auth-library/node_modules/request/request.js:1003:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
```
Not sure it comes from my code or the service account settings, but the 500 return code doesn't help me find out, even looks like a app engine error....
Did someone tried something like that or can point me to some relevant infos I coudn't find .(Spent almost all the day in the Google api docs, sandbox, etc... to try to set this up)....
Thx.

**Comment by cedric-b** [comment]
My mistake, forgot to replace 'my_customer' placeholder by the real customer id.
