### ISSUE TITLE
Using jwtClient.authenticate() behind a proxy results in ETIMEDOUT error

### ISSUE THREAD

**Issue by hdpinto** [google/google-api-nodejs-client#705]
I've been attempting to authenticate requests using the JWT client.

I've set up my request:

```javascript
var google = require('googleapis');
var key = require('./config/key.json');

var proxy = {
    user: 'user',
    pass: 'pass',
    hostname: 'foobar.com',
    portnumber: '8080'
}

// Set up the proxy as per the documentation
google.options({
    proxy: `http://${proxy.user}:${proxy.pass}@${proxy.hostname}:${proxy.portnumber}`
});

// Scope to GA
var scope = 'https://www.googleapis.com/auth/analytics.readonly';

// Set up the client as per the documentation
var jwtClient = new google.auth.JWT(
    key.client_email,
    null,
    key.private_key,
    scope,
    null
);

// I try to get an access tokens, this is where it hangs.
jwtClient.authorize(function (err, tokens) {
    if (err) {
        // There is a long pause, followed by an error here
        console.log(err);
        return;
    }
    // some code
}
```

I've tracked the execution (through breakpoints) through the googleapi library and its dependencies, but nowhere do I see a mention of that proxy option I set above. The error logged to the console:

```text
{ 
  Error: connect ETIMEDOUT 172.217.1.109:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.217.1.109',
  port: 443
}
```

I've tried googling around, but I haven't seen anyone else with this exact issue. I apologize if there's some silly reason the request is timing out, but I really am at wit's end with this problem.

**Comment by hdpinto** [comment]
So after some more digging, I realized [#336](https://github.com/google/google-api-nodejs-client/issues/336) offered some insight.

You can configure a proxy through `HTTP_PROXY` and `HTTPS_PROXY` environment variables. This is not desirable for everyone and I wish the following code just worked for all cases:
```javascript
google.options({
    proxy: `http://${proxy.user}:${proxy.pass}@${proxy.hostname}:${proxy.portnumber}`
});
```
