### ISSUE TITLE
Large spreadsheets (> 100mb) cause `toString` error with `buffer.js`

### ISSUE THREAD

**Issue by qodesmith** [google/google-api-nodejs-client#729]
Using the `googleapis` module to request a spreadsheet will throw an error on larger spreadsheets. Here's my working example:

```JavaScript
const google = require('googleapis');
const sheets = google.sheets('v4');

function get_sheet(req, res) {
  let id = req.params.id;

  getAuth(res, getSheet);

  function getSheet(auth) {
    sheets.spreadsheets.get({
      auth: auth,
      includeGridData: true,
      spreadsheetId: id
    }, function(err, spreadsheet) {
      if (err) { return res.status(500).send({getSheet: err}); }
      res.send(spreadsheet); // <-- This never gets hit for larger spreadsheets
    });
  }
}
```

I started off with a spreadsheet containing 1 sheet with KR columns and 77 rows (23,408 total cells). Running `get_sheet` for that spreadsheet will `res.send` fine. I duplicated the 1st sheet and tried again. Fine. So on and so forth up to 8 sheets on the spreadsheet worked fine. Once I hit 9 sheets, this is the error I would get in node:

```
buffer.js:528
    throw new Error('"toString()" failed');
    ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:528:11)
    at BufferList.toString (/Users/aaron/L2/Datatron/node_modules/bl/bl.js:166:33)
    at Request.<anonymous> (/Users/aaron/L2/Datatron/node_modules/request/request.js:1035:36)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/aaron/L2/Datatron/node_modules/request/request.js:1003:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

I assigned the response to `window.res`. The last successful response (8 sheets) yielded this size: `JSON.stringify(res).length // 95773246`, so just about 95 megs. Each additional sheet seemed to add about 11 megs to the size. In any case, is there a hard-limit on the size of a spreadsheet that can be retrieved? I've heard of much larger spreadsheets being used, so I'm not sure what's going wrong and why `buffer.js` is screaming at me.

**Comment by qodesmith** [comment]
A workaround that performs _much_, much faster and doesn't freak `buffer.js` out. My original request for larger sheets utilizing `includeGridData: true` was taking upwards of 2 minutes to complete. The code below, using `includeGridData: false` along with `sheets.spreadsheets.values.get` concludes in under a second:

```JavaScript
function get_sheet(req, res) {
  let id = req.params.id;

  getAuth(res, getSheet);

  function getSheet(auth) {
    sheets.spreadsheets.get({
      auth: auth,
      includeGridData: false, // No longer requesting the grid data. Super fast!
      spreadsheetId: id
    }, function(err, spreadsheet) {
      if (err) { return res.status(500).send({getSheet: err}); }

      let promises = spreadsheet.sheets.map(sheet => {
        let title = sheet.properties.title;
        let lastColumn = columnsToA1(sheet.properties.gridProperties.columnCount);
        let lastRow = sheet.properties.gridProperties.rowCount;

        // Get the full range of cells for each individual sheet - also super fast!
        return new Promise((resolve, reject) => {
          sheets.spreadsheets.values.get({
            auth: auth,
            spreadsheetId: id,
            majorDimension: 'ROWS',
            range: `'${title}'!A1:${lastColumn}${lastRow}`
          }, (err, results) => {
            if (err) { return reject(err); }

            sheet.data = results;
            resolve(sheet);
          });
        });
      });

      Promise.all(promises)
        .then(results => res.send(results))
        .catch(err => res.status(500).send({getSheet: err}));
    });
  }

  // This can accomodate A through ZZ (701 columns).
  // This meets our use case, but feel free to write something else more versatile.
  function columnsToA1(num) {
    num--; // Ensure we're 1-indexed.

    // 0 - 25 represented as A - Z
    // 26+ as AA, AB, AC...
    let letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

    // First letter in a 2-letter value.
    let set = Math.floor(num / 26); // What set of 26 are we on.
    let setLetter = set > 0 ? letters[set - 1] : ''; // Convert `set` to a letter.

    // 2nd letter in a 2-letter value or the only letter at all.
    let letterNum = num % 26;
    let letter = letters[letterNum];
    return setLetter + letter;
  }
}
```
