### ISSUE TITLE
Unable to create app script project

### ISSUE THREAD

**Issue by tavakyan** [google/google-api-nodejs-client#751]
I was trying the code snippet shown here https://github.com/google/google-api-nodejs-client/issues/680 in order to generate an app script project in my google drive using the google-api-nodejs-client.  

In my api call I have the following snippet:

```js
// Create worksheet in project folder
        let fileMetaData = {
          'name' : 'staging',
          'mimeType' : 'application/vnd.google-apps.spreadsheet',
          parents: [file.id]
        }
        drive.files.create({
          resource: fileMetaData,
          fields: 'id'
        }, function(err, sheetFile) {
          if (err) {
            console.log(err)
          } else {
            req.body.googleSheetId = sheetFile.id
          }
        })

        // Create script project in project folder
        drive.files.create({
          resource: {
            name: 'cba.gs',
            mimeType: 'application/vnd.google-apps.script+json'
          },
          media: {
            mimeType: 'application/vnd.google-apps.script+json',
            body: JSON.stringify({
              files: [
                {
                  source: fs.readFileSync('api/services/google/cba.gs', { encoding: 'utf-8' }),
                  name: 'cba',
                  type: 'server_js'
                }
              ]
            })
          }
        }, function (err, file) {
          console.log(err)
          console.log(file)
        });
// ...
}
```
The worksheet creation using the drive client works, but the creation of the script project does not work and returns the following error: 

```
{ Error: Internal Error
    at Request._callback (.../node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (.../node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (.../node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (.../node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 500,
  errors:
   [ { domain: 'global',
       reason: 'internalError',
       message: 'Internal Error' } ] }
```

I'm using googleapis V19.0.0 and created a service account with a JSON file like this:

```
{
  "type": "service_account",
  "project_id": "project-id-xxxxxx",
  "private_key_id": "5677810",
  "private_key": "-----BEGIN PRIVATE KEY-----
stuff
-----END PRIVATE KEY-----\n",
  "client_email": "serviceaccount@project-id.iam.gserviceaccount.com",
  "client_id": "12345",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/serviceaccount%40project-id.iam.gserviceaccount.com"
}
```

I'm using 

```
export const jwtClient = new google.auth.JWT(
    key.client_email,
    null,
    key.private_key,
    SCOPES,
    null
  );
```
to load the JSON file and it seems to work in other API calls.  

What am I missing/doing wrong?  Is it a possible JWT support problem or something else?  Also, I'm not using a google for business account, just my personal google account at the moment.

Thanks in advance!

**Comment by ace-n** [comment]
cc @erickoledadevrel

**Comment by erickoledadevrel** [comment]
We're not returning a great error message, but the underlying cause is that service accounts can't own scripts. You'll need to create the scripts under a regular user account instead.

**Comment by tavakyan** [comment]
@erickoledadevrel Thank you, will try it this way.
