### ISSUE TITLE
Drive API --> move file --> Error: options.uri is a required argument

### ISSUE THREAD

**Issue by gfhuertac** [google/google-api-nodejs-client#811]
Hi,
I am having a problem moving a file from one folder to another. Two weeks ago this sample code worked OK:

```
function move(auth, file_id, target_folder, callback) {
    let drive = google.drive('v3');
    drive.files.get({
        auth: auth,
        fileId: file_id,
        fields: 'parents'
    }, function(err, file) {
        if (err) return callback(err);
        // Move the file to the new folder
        let previous_parents = file.parents.join(',');
        drive.files.update({
            auth: auth,
            fileId: file_id,
            addParents: target_folder,
            removeParents: previous_parents,
            fields: 'id, parents'
        }, callback);
    });
}
```

The first request works OK, however the second one (update) is not working now, and throws the following error:

```
Error: options.uri is a required argument
    at Request.init (/Volumes/backup/coal_app/node_modules/request/request.js:234:31)
    at new Request (/Volumes/backup/coal_app/node_modules/request/request.js:130:8)
    at request (/Volumes/backup/coal_app/node_modules/request/index.js:54:10)
    at DefaultTransporter.request (/Volumes/backup/coal_app/node_modules/google-auth-library/lib/transporters.js:58:10)
    at OAuth2Client._makeRequest (/Volumes/backup/coal_app/node_modules/google-auth-library/lib/auth/oauth2client.js:390:27)
    at authCb (/Volumes/backup/coal_app/node_modules/google-auth-library/lib/auth/oauth2client.js:374:19)
    at OAuth2Client.getRequestMetadata (/Volumes/backup/coal_app/node_modules/google-auth-library/lib/auth/oauth2client.js:281:12)
    at OAuth2Client.request (/Volumes/backup/coal_app/node_modules/google-auth-library/lib/auth/oauth2client.js:379:15)
    at Object.createAPIRequest [as default] (/Volumes/backup/coal_app/node_modules/googleapis/lib/apirequest.js:150:26)
    at Object.update (/Volumes/backup/coal_app/node_modules/googleapis/apis/drive/v3.js:736:40)
```

I am testing this with Node 6.11.2, on Mac and on Heroku.
I tried request versions 2.53, 2.7 and 2.81.
Any help is appreciated!

Thanks!

**Comment by bantini** [comment]
It works on Mac with Node 8.5.0 and request v3.10.10. What are you doing for the second callback?

This is what is working for me:

```javascript
function move(auth) {
   var file_id = "<id of google document>";
   var target_folder = "<id of google folder where you want to copy the document>";
    var drive = google.drive('v3');
    drive.files.get({
        auth: auth,
        fileId: file_id,
        fields: 'parents'
    }, function(err, file) {
        if (err){
          console.log("ERROR while fetching parent");
        } else {
        // Move the file to the new folder
        var previous_parents = file.parents.join(',');
        drive.files.update({
            auth: auth,
            fileId: file_id,
            addParents: target_folder,
            removeParents: previous_parents,
            fields: 'id, parents'
        }, function(err, file){
          if (err){
            console.log("ERROR while updating parent");
          } else {
            
            console.log("Success");
          }
        });
      }
    });
}
```

**Comment by gfhuertac** [comment]
Thanks for your reply.
Based on your replay I debugged my code and I found the error in the method that called the move function.
I do not know if it is a bug or I am using waterfall incorrectly, but when using spreadsheets.values.update I am receiving two values back, not just the response as mentioned in the documentation (https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/update), so this code failed:

```
        async.waterfall([
            function(cb) {
              sheets.spreadsheets.values.update({
                  auth: auth,
                  spreadsheetId: ss_id,
                  range: sheet_id + '!A:Z',
                  valueInputOption: 'USER_ENTERED',
                  resource: body
              }, cb);
            }, function(values, cb) {
                if (!cb && typeof values == 'function') cb = values;
                move(auth, ss_id, folder_id, cb);
            }, function(file, ignore, cb) {
                if (!cb && typeof ignore == 'function') cb = ignore;
                if (!cb && typeof file == 'function') cb = file;
                cb(undefined, {
                    id: ss_id,
                    url: url
                });
            }
        ], callback);
```
 
I changed 

```
    }, function(values, cb) {
```

to

```
    }, function(values, ignore, cb) {
```

and it worked.

BTW, latest version of request is [2.81.1](https://github.com/request/request/blob/master/package.json#L10), which I tried. I could not find the version you mention in your reply.
