### ISSUE TITLE
backendError 500 when using the 

### ISSUE THREAD

**Issue by ajudi** [google/google-api-nodejs-client#831]
I'm getting the following error when trying to use the webmaster.searchanalytics api:

```
{ Error: Backend Error
    at Request._callback (/home/tom/Programming/MagpieMicroService/node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (/home/tom/Programming/MagpieMicroService/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/tom/Programming/MagpieMicroService/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/tom/Programming/MagpieMicroService/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
  code: 500,
  errors: 
   [ { domain: 'global',
       reason: 'backendError',
       message: 'Backend Error' } ] }
```
Code is the following:

```
'use strict';

var google = require('googleapis');
var fs = require('fs');
var key = require('./client_secret.json');
var prompt = require('prompt');

var tokens_file = './tokens/tokens.json';
var scopes = [
    'https://www.googleapis.com/auth/webmasters'
];

var OAuth2 = google.auth.OAuth2;
var oauth2Client = new OAuth2(
    key.installed.client_id,
    key.installed.client_secret,
    key.installed.redirect_uris[0],
);



fs.readFile(tokens_file, 'utf8', (err, data)=>{
    if (err) {
        console.log('No token file: ',err);
        var url = oauth2Client.generateAuthUrl({
            access_type: 'offline',
            scope: scopes,
        });
        console.log(
            'Head to the URL ', 
            url, 
            ' and paste the authorization code in:'
        );
        prompt.start();
        prompt.get(['authorizationCode'],(err, result)=>{
            if (err) {return console.log(err);}
            var code = result.authorizationCode;
            oauth2Client.getToken(code, (err, tokens)=>{
                if (err) {return console.log(err);}
                console.log(tokens)
                fs.writeFile(
                    tokens_file, 
                    JSON.stringify(tokens), 
                    (err)=>{
                        if (err) {return console.log('Error ', err);}
                        console.log('Tokens Saved')
                    }
                );
                oauth2Client.setCredentials({
                    access_token: tokens.access_token,
                    refresh_token: tokens.refresh_token
                });
                //Make the authorised call here
                const webmasters = google.webmasters('v3');
                let date = new Date();
                let startDate = new Date(date-7);
                let endDate = new Date(date-7);
                let params = {
                    'startDate': "2017-9-25",//startDate.toISOString(),
                    'endDate': "2017-9-26",//endDate.toISOString(),
                    'dimensions': ['query', 'device'],
                    'rowLimit': 5000,
                    'startRow': 0,
                    'siteUrl': encodeURIComponent('http://www.url.com/de/'),
                    'auth': oauth2Client,
                };
                console.log(params.siteUrl);
                console.log(params);
                webmasters.searchanalytics.query(params,function(err, data){
                    if (err) return console.log('There was an error: ', err);
                    console.log('This is the data: ', data);
                });
            });

        });
        return;
    };
    console.log('onfile')
    var tokens = JSON.parse(data);
    console.log('tokens: ', tokens);
    oauth2Client.setCredentials({
        access_token: tokens.access_token,
        refresh_token: tokens.refresh_token
    });
    console.log(oauth2Client)
    //Make the authorised call here
    // google.options({auth:oauth2Client});
    const webmasters = google.webmasters('v3');
    let date = new Date();
    let startDate = new Date(date-7);
    let endDate = new Date(date-7);
    let params = {
        'startDate': "2017-09-25",//startDate.toISOString(),
        'endDate': "2017-09-26",//endDate.toISOString(),
        'dimensions': ['query', 'device'],        
        'rowLimit': 5000,
        'startRow': 0,
        'siteUrl': encodeURIComponent('http://www.url.com/de/'),
        'auth': oauth2Client,
    };
    console.log(params.siteUrl);
    console.log(params);
    webmasters.searchanalytics.query(params,function(err, data){
        if (err) return console.log('There was an error: ', err);
        console.log('This is the data: ', data);
    });
});
```

**Comment by russellsean** [comment]
Hi @ajudi 

From Google's [documentation](https://developers.google.com/drive/v3/web/handle-errors#500_backend_error) (See Error Code: 500), this backEnd Error happens when:
> ...the client periodically retries a failed request over an increasing amount of time.

Can you wrap this: 
`    webmasters.searchanalytics.query(params,function(err, data){
        if (err) return console.log('There was an error: ', err);
        console.log('This is the data: ', data);
    });`

in a try/catch, log the error and post is here for review?

**Comment by ajudi** [comment]
It doesn't actually produce an error sadly. I tried the following:

```
try{
            webmasters.searchanalytics.query(params, {}, function(err, data){
                if (err) return console.log('There was an error: ', err);
                console.log('This is the data: ', data);
            });
        }catch(e){
            console.log('caught error')
            console.log(e)
        }
```

I guess because it's being passed to the callback?

**Comment by ajudi** [comment]
It also seems to be writing a number of files in my directory. Not anything that I can unencode or recognise. All seem to be in the same format. 
```
107.021.227.111.00443-192.168.123.147.39358
```
Any ideas why that might be.

**Comment by ajudi** [comment]
I looked in to this further as our Python implementation works. It seems as though it's an error in the javascript libraries. Can't really tell where the error is but if you try and use the API explorer on the google website it's also broken. Works fine if you just use POST from the request library with the key I get from auth. It's not a rate limiting issue the API is broken.

**Comment by bantini** [comment]
@ajudi It's curious that the Javascript and API explorer fails while the python code succeeds. Can you share the python code that works? Might help us debug the issue.

**Comment by ajudi** [comment]
Sure.

```
import argparse
import csv
import datetime
import hashlib
import httplib2

from apiclient import discovery
from oauth2client import client
from oauth2client.file import Storage
from oauth2client import tools

import settings


def execute_request(service, client_url, request):
    """
    Execute a searchAnalytics.query request.
    :param service:       The webmasters service to use when executing the
                          query.
    :param client_url:    The site or app URI to request data for.
    :param request:       The request to be executed.
    :returns:             An array of response rows.
    """
    return service.searchanalytics().query(siteUrl=client_url,
                                           body=request).execute()


def get_credentials():
    """
    Check for credentials, in the storage data file.
    If no credentials are stored of if the stored credentials
    are invalid, new credentials are return by the function run_flow().
    The new credentials are also stored in the storage argument, which
    updates the file associated with the Storage object.
    :returns credentials:    credentials object
    """
    flow = client.flow_from_clientsecrets(settings.CLIENT_SECRET,
                                          scope=settings.SCOPE,
                                          redirect_uri=settings.REDIRECT_URI)

    storage = Storage(settings.STORAGE_FILE)
    credentials = storage.get()
    if credentials is None or credentials.invalid:
        parser = argparse.ArgumentParser(parents=[tools.argparser])
        flags = parser.parse_args(['--noauth_local_webserver'])
        credentials = tools.run_flow(flow=flow, storage=storage, flags=flags)

    return credentials


def build_service_object():
    """
    Build the service object for google drive.
    The service object is constructed with methods specific
    to the given api, in this case, google drive.
    :returns service:    service object for google drive api
    :example:
    >>> from apiclient import discovery
    >>> service = discovery.build('drive', 'v2'...)
    """
    credentials = get_credentials()
    http_auth = credentials.authorize(httplib2.Http())
    service = discovery.build('webmasters', 'v3', http_auth)

    return service


def set_date_range():
    """
    Set the date range available by querying the Search Console API with a
    simple query.
    This will return the list of available dates, which should
    always be 90 days in length. There is an offset of between 3 and 6 days
    from todays date that needs to be accounted for, hence starting the query
    on 2015-01-01.
    This function is designed to gather the data by 30 day period, i.e. day 0
    to day 29, day 30 to day 59, etc.
    :returns query_dates:    List of tuples, containing string formatted
                             dates.
    """
    list_of_dates = []
    end_date = datetime.date.today().strftime('%Y-%m-%d')
    request_body = {'startDate': '2015-01-01',
                    'endDate': end_date,
                    'dimensions': ['date']}
    service = build_service_object()
    response = execute_request(service, settings.CLIENT_URL, request_body)

    for row in response['rows']:
        list_of_dates.append(row['keys'][0])

    query_dates = [(list_of_dates[0], list_of_dates[29]),
                   (list_of_dates[30], list_of_dates[59]),
                   (list_of_dates[60], list_of_dates[-1])]
    return query_dates


def query_search_console_data(dates, service, device):
    """
    Query the Search Console using ignore characters, and date ranges.
    Returns raw unencoded data.
    :param dates:          dates in tuple to query
    :param service:        service object
    """
    list_data = []

    print 'Requesting {} data'.format(device)
    for character in settings.IGNORE:
        request_body = {
            'startDate': '{}'.format(dates[0]),
            'endDate': '{}'.format(dates[1]),
            'dimensions': ['query',
                           'device'],
            'dimensionFilterGroups': [
                {'groupType': 'and',
                    'filters': [
                        {'dimension': 'query',
                         'operator': 'notContains',
                         'expression': character},
                        {'dimension': 'device',
                         'operater': 'equals',
                         'expression': device}]}],
            'rowLimit': 5000}

        response = execute_request(service,
                                   settings.CLIENT_URL,
                                   request_body)
        encoded_response = encode_response(response)
        metrics_list = row_builder(encoded_response, dates, list_data)
    print 'Returning metrics_list'
    return metrics_list
```
