### ISSUE TITLE
NPM Install googleapis: Missing child_process

### ISSUE THREAD

**Issue by ChaddPortwine** [google/google-api-nodejs-client#835]
`npm install googleapis --save` does not install all dependencies.

**I get the following when installing:**

```
Silver-Sliver:people-is dchaddportwine$ npm install googleapis --save

> unix-dgram@0.2.2 install /Users/dchaddportwine/Sites/people-is/node_modules/unix-dgram
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
In file included from ../src/unix_dgram.cc:5:
In file included from ../node_modules/nan/nan.h:182:
../node_modules/nan/nan_maybe_43_inl.h:221:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/dchaddportwine/.node-gyp/6.10.2/include/node/v8.h:3031:3: note: 'CloneElementAt' has been explicitly marked deprecated here
  V8_DEPRECATED("Cloning is not supported.",
  ^
/Users/dchaddportwine/.node-gyp/6.10.2/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/unix_dgram.cc:5:
In file included from ../node_modules/nan/nan.h:188:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/dchaddportwine/.node-gyp/6.10.2/include/node/v8.h:4008:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
  ^
/Users/dchaddportwine/.node-gyp/6.10.2/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/unix_dgram.cc:5:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:1927:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/dchaddportwine/.node-gyp/6.10.2/include/node/v8.h:2750:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/dchaddportwine/.node-gyp/6.10.2/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
3 warnings and 4 errors generated.
make: *** [Release/obj.target/unix_dgram/src/unix_dgram.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dchaddportwine/Sites/people-is/node_modules/unix-dgram
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
people-is@1.0.0 /Users/dchaddportwine/Sites/people-is
└── googleapis@22.2.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.2 (node_modules/unix-dgram):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```
**I get the following when running** `npm run dev` **with this code**, `var googleapis = require('googleapis'); ,` **included**:

```
Silver-Sliver:people-is dchaddportwine$ npm run dev

> people-is@1.0.0 dev /Users/dchaddportwine/Sites/people-is
> node build/dev-server.js

> Starting dev server...


 ERROR  Failed to compile with 8 errors                                                                                                                                                              4:30:26 PM

These dependencies were not found:

* fs in ./~/googleapis/lib/googleapis.js, ./~/googleapis/lib/discovery.js and 5 others
* child_process in ./~/google-auth-library/lib/auth/googleauth.js

To install them, you can run: npm install --save fs child_process
> Listening at http://localhost:8080
```

Seems like a bug. `npm install` then `npm dev run` shouldn't require extra installation steps, right?

**Comment by ChaddPortwine** [comment]
This became an issue after I updated macOS Sierra 10.12.6, which updated Command Line Tools  for Xcode - Version 9.0.

**Comment by bantini** [comment]
@ChaddPortwine What is your node and npm versions?

**Comment by ChaddPortwine** [comment]
@bantini here is what I see:

```
Silver-Sliver:people-is dchaddportwine$ npm --version
4.2.0
Silver-Sliver:people-is dchaddportwine$ node --version
v6.10.2
```

**Comment by bantini** [comment]
@ChaddPortwine I have exactly the same configuration (after installing your version of node and npm using nvm), and I was able to install _googleapis_ in one step. I suspect this might be a one-off issue on how command-line-tools is set-up. However, I will keep this issue open for sometime in case someone else faces it.

**Comment by ChaddPortwine** [comment]
I tried working with **brew**. Spoiler, _this didn't help_. Going to try fixing `.node-gyp` next.

**Homebrew**
I ran `brew update` which updated the node formula.

I ran `brew doctor` and got this message:

```Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  node
```

I ran `brew link node` and got:

```Linking /usr/local/Cellar/node/7.9.0... 
Error: Could not symlink bin/node
Target /usr/local/bin/node
already exists. You may want to remove it:
  rm '/usr/local/bin/node'

To force the link and overwrite all conflicting files:
  brew link --overwrite node
```

I removed` /usr/local/bin/node` and tried `brew link node` again and got:

```
Linking /usr/local/Cellar/node/7.9.0... 
Error: Could not symlink include/node/android-ifaddrs.h
Target /usr/local/include/node/android-ifaddrs.h
already exists. You may want to remove it:
  rm '/usr/local/include/node/android-ifaddrs.h'

To force the link and overwrite all conflicting files:
  brew link --overwrite node

To list all files that would be deleted:
  brew link --overwrite --dry-run node
```

I ran `brew link --overwrite --dry-run node` and a lot of files where listed.

I ran `brew link --overwrite node` and got:
```
Linking /usr/local/Cellar/node/7.9.0... 144 symlinks created
```

I ran `brew doctor` again and got:

```
Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install openssl@1.1
```

I ran `brew install openss@1.1`

Now, brew is happy, but the node-gyp error persists when I try `npm install googleapis --save`

Moving on to try fixing node-gyp....

**Comment by ChaddPortwine** [comment]
I'm assuming something is broken in my environment. I used brew to uninstall/install node, deleted 
 the node_modules folder in the project, and ran npm install for a fresh set. But no change.

I submitted a bug to node-gyp. The response was:

> The xcodebuild lines in the log lines are red herrings, you can ignore them. It says 'error' but they're really just informational from node-gyp's perspective.

>The issue is that you're trying to install an old version of unix-dgram, v0.2.2. Update to the latest - v2.0.1 - and all should be well.

I uninstalled and then ran `npm install unix-dgram` but `unix-dgram@0.2.2 install` in the first line looks wrong.

The unix-dgram devs, after seeing my output below suggested,

> It's because the package you're trying to install, ain2, depends on an old version of unix-dgram. You'll have to take that up with them.


```
unix-dgram@0.2.2 install /Users/dchaddportwine/Sites/people-is/node_modules/ain2/node_modules/unix-dgram
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
In file included from ../src/unix_dgram.cc:5:
In file included from ../../nan/nan.h:182:
../../nan/nan_maybe_43_inl.h:221:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8.h:3346:3: note: 'CloneElementAt' has been explicitly marked deprecated here
  V8_DEPRECATED("Cloning is not supported.",
  ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/unix_dgram.cc:5:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8.h:4490:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
  ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/unix_dgram.cc:5:
../../nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:1927:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8.h:3026:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/dchaddportwine/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
3 warnings and 4 errors generated.
make: *** [Release/obj.target/unix_dgram/src/unix_dgram.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dchaddportwine/Sites/people-is/node_modules/ain2/node_modules/unix-dgram
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

> unix-dgram@2.0.1 install /Users/dchaddportwine/Sites/people-is/node_modules/unix-dgram
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
  SOLINK_MODULE(target) Release/unix_dgram.node
people-is@1.0.0 /Users/dchaddportwine/Sites/people-is
└─┬ unix-dgram@2.0.1
  ├── bindings@1.1.1
  └── nan@2.3.5

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.2 (node_modules/ain2/node_modules/unix-dgram):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unix-dgram@0.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

Doesn't it look like node-gyp is still the issue?

**Comment by bantini** [comment]
@ChaddPortwine Do you have Xcode installed? Because if you don't, that might be the only difference between your settings and mine.

**Comment by ChaddPortwine** [comment]
@bantini, no I do not have XCode installed. I only have the xcode command line tools. 

## Reinstalled Node/NPM
Something in **my project** setup must be very broken, and I'm probably on my own. I followed [these instructions](https://www.kevinallenrodriguez.com/blog/fixing-npm-on-macos-for-homebrew-users/) for a "clean install" of node and npm.

## I was able to install googleapis
Into a new folder: `npm init`, `npm install` `npm install googleapis --save`

```
Silver-Sliver:test-googleapis dchaddportwine$ npm install googleapis --save
+ googleapis@22.2.0
added 54 packages in 12.334s
```

Thank you for looking at this, @bantini.

**Comment by ChaddPortwine** [comment]
Again, this is probably **my** issue, but...

`npm install googleapis --save` worked with no errors.

**However**, `npm run dev` suffers from child_process issues.

```
Silver-Sliver:test-googleapis dchaddportwine$ npm run dev

> test-googleapis@1.0.0 dev /Users/dchaddportwine/Startup/test-googleapis
> node build/dev-server.js

> Starting dev server...

 DONE  Compiled successfully in 3751ms                                                         9:28:53 AM

> Listening at http://localhost:8080



 WAIT  Compiling...                                                                            9:30:47 AM



 ERROR  Failed to compile with 13 errors                                                       9:30:54 AM

These dependencies were not found:

* child_process in ./node_modules/google-auth-library/lib/auth/googleauth.js
* fs in ./node_modules/google-auth-library/lib/auth/googleauth.js, ./node_modules/google-p12-pem/index.js
 and 5 others
* net in ./node_modules/forever-agent/index.js, ./node_modules/tough-cookie/lib/cookie.js and 1 other
* tls in ./node_modules/forever-agent/index.js, ./node_modules/tunnel-agent/index.js

To install them, you can run: npm install --save child_process fs net tls


 WAIT  Compiling...                                                                            9:52:12 AM



 ERROR  Failed to compile with 13 errors                                                       9:52:13 AM

These dependencies were not found:

* child_process in ./node_modules/google-auth-library/lib/auth/googleauth.js
* fs in ./node_modules/google-auth-library/lib/auth/googleauth.js, ./node_modules/google-p12-pem/index.js
 and 5 others
* net in ./node_modules/forever-agent/index.js, ./node_modules/tough-cookie/lib/cookie.js and 1 other
* tls in ./node_modules/forever-agent/index.js, ./node_modules/tunnel-agent/index.js

To install them, you can run: npm install --save child_process fs net tls
```

**Comment by ChaddPortwine** [comment]
## Pull and build my test project from git:

https://github.com/ChaddPortwine/test-googleapis

This is a very simple Vue project to demonstrate my `googleapis` issues.

Have I done something stupid?

**Comment by nickreynke** [comment]
Any updates on this? I got the same issue, also working with Vue but that does not have anything to do with the problem I think. Installing `googleapis` does work fine but running `npm run dev` also returns me a pretty similar output to yours @ChaddPortwine

```
ERROR  Failed to compile with 8 errors                                                                                                                                                  15:33:28

These dependencies were not found:

* fs in ./~/googleapis/lib/googleapis.js, ./~/googleapis/lib/discovery.js and 5 others
* child_process in ./~/google-auth-library/lib/auth/googleauth.js

To install them, you can run: npm install --save fs child_process
> Listening at http://localhost:8080
```
