### ISSUE TITLE
Announcement APIs are missing from Classroom

### ISSUE THREAD

**Issue by ashishmodak** [google/google-api-nodejs-client#838]
I am using latest googleapis npm. I tried to call the following function to receive announcements for course.
```js
classroom.courses.announcements.list({
                    auth: oauth2Client,
                    courseId: req.query.id,
                    pageSize: 10
                    }, function(err, response) {
                    if (err) {
                    console.log('The API returned an error: ' + err);
                    callback(null, [])
                    return;
                    }
                    callback(null, response);
                });
``` 
I am receiving following error.:

```
TypeError: Cannot read property 'list' of undefined
    at /app/routes.js:73:48
    at /node_modules/async/dist/async.js:3853:24
    at eachOfArrayLike (/node_modules/async/dist/async.js:1003:9)
    at eachOf (/node_modules/async/dist/async.js:1051:5)
    at _parallel (/node_modules/async/dist/async.js:3852:5)
    at Object.parallelLimit [as parallel] (/node_modules/async/dist/async.js:3935:5)
    at Object.handle (/app/routes.js:28:15)
    at next_layer (/node_modules/express/lib/router/route.js:103:13)
    at Object.isLoggedIn [as handle] (/app/routes.js:237:16)
    at next_layer (/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:107:5)
    at /node_modules/express/lib/router/index.js:195:24
    at Function.proto.process_params (/node_modules/express/lib/router/index.js:251:12)
    at next (/node_modules/express/lib/router/index.js:189:19)
    at next (/node_modules/express/lib/router/index.js:166:38)
    at next (/node_modules/express/lib/router/index.js:166:38)`
```

I have checked node_modules\googleapis\apis\classroom\v1.js file it doesn't contain any announcement related APIs.

Am I missing something?

**Comment by JustinBeckwith** [comment]
Support for `announcements` on this API got added in this commit: 
https://github.com/google/google-api-nodejs-client/commit/af84152a6f28a113a1ae8b5949e5feab113a74dd#diff-62cb437586fd91307656d45639388778

We just need to cut a new release.  @jmdobry what do you think?

**Comment by JustinBeckwith** [comment]
This was addressed with the latest release.  Thanks!

**Comment by ashishmodak** [comment]
Thanks @JustinBeckwith
