### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by cimdalli** [google/google-api-nodejs-client#848]
In order to use that package in typescript based project, I use **require** import statement

`const google = require('googleapis')`

However when I try to run tests which are written with **jest**, I am getting that error

```
Test suite failed to run

    <project_root>/node_modules/googleapis/lib/discovery.ts:14
    import generatorUtils from '../scripts/generator_utils';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (node_modules/googleapis/lib/googleapis.js:17:21)
      at Object.<anonymous> (src/service/gaReport.service.ts:7:16)
```

It seems try to compile 'googleapis' code under 'node_modules' folder, however I already ignored it.

**package.json**
```
 "transform": {
      "^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
 },
 "testRegex": "(/__tests__/.*|(\\.|/)(test1|spec1|jest))\\.(tsx?)$",
 "testPathIgnorePatterns": [
      "<rootDir>/node_modules"
 ], 
```
**tsconfig.json**
```
  "exclude": [
    "build",
    "node_modules",
    "src/shared/ncshared",
    "src/scripts"
  ]
```

**Versions**
```
    "typescript": "~2.5.0"
    "jest": "^21.2.1",
    "ts-jest": "^21.1.4",
```

**Comment by cimdalli** [comment]
I found the problem, it's not about 'googleapis' in fact. When 'googleapis' is required, one of its dependencies ('./discovery') is also been resolving by **jest**. But in lib directory, there are two files that match 'discovery' name. (.js and .ts files). Module resolution process choose .ts file depend on jest config. At the end, it tries to resolve 'discovery.ts' which is not correct.

To fix it; in 'package.json' change **jest** config in that order:

```
"moduleFileExtensions": [
      "js",
      "jsx",
      "ts",
      "tsx",
      "json"
],
```
