### ISSUE TITLE
Google Drive API v3 update method fails when read stream is passed as request body

### ISSUE THREAD

**Issue by graymur** [google/google-api-nodejs-client#850]
I'm trying to update existing file with following code:

```
const readStream = fs.createReadStream('./tests/data/image-sample.jpg');

drive.files.update({
	uploadType: 'media',
	fileId: file.id, // id of existing file
	media: {
		mimeType: 'image/jpeg',
		body: readStream
	}
}, function (err, data) {
	if (err) {
		console.error(err);
	} else {
		console.log(data);
	}
});
```

I get this error: 

```
Error: write after end
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:439:15)
    at Request.write (.../node_modules/request/request.js:1514:27)
    at ReadStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at onread (fs.js:2004:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)
```

If I read the whole file like this:

```
const fileContents = fs.readFileSync('./tests/data/image-sample.jpg');
```
and replace `body: readStream` with `body: fileContents` in the example above, file is updated without problems.

`drive.files.create` works with both stream and whole file's body.

Thank you.

**Comment by bantini** [comment]
@graymur This worked for me:
https://gist.github.com/bantini/c5de8673e8a85642dda383247b4b37bb

**Comment by bantini** [comment]
Closing because there was no activity for 7 days. Assuming that the problem was solved. Feel free to reopen the issue if the problem persists.
