### ISSUE TITLE
Gmail API: users.watch - topicName required.

### ISSUE THREAD

**Issue by felicienb** [google/google-api-nodejs-client#976]
I don't understand why the call of _gmail.users.watch_ answers me that topicName is required:

**CODE**

```
  var gmail = google.gmail("v1");
  gmail.users.watch({
    auth: auth,
    userId: "me",
    resource: {
      topicName: projects/{myproject}/topics/{mytopic},
    }
  }, function(err, response) {
    if (err) {
      errorPrinter('setWatch', err);
      return;
    }
    printer(response);
   });
  }
```

**RESPONSE**

```
Error on request: setWatch, Error: { Error: topicName required
    at new RequestError (/Users/felicien/Artefact/Estee-Lauder/Node/node_modules/google-auth-library/lib/transporters.js:34:42)
    at Request._callback (/Users/felicien/Artefact/Estee-Lauder/Node/node_modules/google-auth-library/lib/transporters.js:96:27)
    at Request.self.callback (/Users/felicien/Artefact/Estee-Lauder/Node/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/felicien/Artefact/Estee-Lauder/Node/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/felicien/Artefact/Estee-Lauder/Node/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
  code: 400,
  errors: 
   [ { domain: 'global',
       reason: 'invalidArgument',
       message: 'topicName required' } ] }
```

And I had the same problem with _gmail.user.history.list_ but I could bypass it by overcharging the url because it is a GET request, so I could give the parameters in the url query.

I also tried to use the HTTP request, but it seems that I don't use the good _access_token_,  whereas I am using the one creating by the API and it works perfectly on user.getProfile.

**CODE** 

```
function setWatch(auth) {
  request({
  url: "https://content.googleapis.com/gmail/v1/users/me/watch?access_token=" + auth.credentials.access_token,
  method: "POST",
  data: {
    topicName: config.topicInput,
  },
  json: true
}, function(err, response) {
  if(err) {
    errorPrinter("watch", err);
  } else {
  printer(response);
  }
});
```

**RESPONSE**

```
  body: 
   { error: 
      { errors: 
         [ { domain: 'global',
             reason: 'authError',
             message: 'Invalid Credentials',
             locationType: 'header',
             location: 'Authorization' } ],
        code: 401,
        message: 'Invalid Credentials' } } }
```

Any help ?

Félicien

**Comment by juggernaut451** [comment]
experiencing same issue

**Comment by workmaster2n** [comment]
Downgrading to version 24 works for now. See the linked comment on the PR to see the line of code that breaks this.

**Comment by JustinBeckwith** [comment]
Greetings!  I was able to get this working with the latest version (v27).  You can see a full working example in #1073.

Usually when folks have these kinds of issues, it's because there's a non-compatible version of google-auth-library installed.  Can you please remove `google-auth-library` from your package.json, run `npm install`, and verify you're still having issues?
