### ISSUE TITLE
GMAIL API: Getting history list error

### ISSUE THREAD

**Issue by juggernaut451** [google/google-api-nodejs-client#978]
{ Error: Missing/invalid parameter: startHistoryId
    at new RequestError (/Users/ashutosh/delete/quick/node_modules/google-auth-library/lib/transporters.js:34:42)
    at Request._callback (/Users/ashutosh/delete/quick/node_modules/google-auth-library/lib/transporters.js:96:27)
    at Request.self.callback (/Users/ashutosh/delete/quick/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/ashutosh/delete/quick/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/ashutosh/delete/quick/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
  code: 400,
  errors: 
   [ { domain: 'global',
       reason: 'invalidArgument',
       message: 'Missing/invalid parameter: startHistoryId' } ] }

**Comment by jrl53** [comment]
I'm getting the same error providing a history ID that works in the API explorer

**Comment by jrl53** [comment]
Putting the startHistoryId parameter inside the {qs:..} object as explained in [issue 469](https://github.com/google/google-api-nodejs-client/issues/469) worked for me!

**Comment by juggernaut451** [comment]
thanks :)

**Comment by DharmendraNaberly** [comment]
https://gmail.googleapis.com/gmail/v1/users/{userId}/history?startHistoryId=178429
